name: Update Bug Report Form

on:
  push:
    branches:
      - qol/bug-report-updater

jobs:
  update-form:
    name: Update Bug Report Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract mod_version from gradle.properties
        id: version
        run: |
          VERSION=$(grep "^mod_version\s*=" gradle.properties | cut -d '=' -f2 | xargs)
          echo "MOD_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update Bug Report Template
        run: |
          FILE=".github/ISSUE_TEMPLATE/1-bug-report.yaml"
          VERSION_LINE="    - $MOD_VERSION"

          if grep -q "$VERSION_LINE" "$FILE"; then
            echo "Version $MOD_VERSION already exists in bug_report.yml"
          else
            awk -v new_version="$VERSION_LINE" '
              /id: version/ { found=1 }
              found && /options:/ {
                print
                print new_version
                found=0
                next
              }
              { print }
            ' "$FILE" > tmp.yml && mv tmp.yml "$FILE"
          fi

      - name: Commit and Push Changes
        run: |
          git config user.name "AIT Updater"
          git config user.email "github-actions@github.com"
          git add .github/ISSUE_TEMPLATE/bug_report.yml
          git commit -m "Update bug report template with mod version $MOD_VERSION"
          git push
